'use client';

import { useState } from 'react';

interface Labels {
  servers: string; locations: string; upstreams: string; globalSettings: string;
  listen: string; serverName: string; root: string; index: string;
  sslCert: string; sslCertKey: string; ssl: string;
  modifier: string; path: string; proxyPass: string; tryFiles: string; returnD: string; alias: string;
  addServer: string; addLocation: string; remove: string;
  upstreamName: string; upstreamServers: string; addUpstream: string; addUpstreamServer: string;
  weight: string; backup: string; address: string;
  gzip: string; clientMaxBodySize: string; keepaliveTimeout: string; workerConnections: string;
  sendfile: string; tcpNopush: string;
  copy: string; copied: string; clear: string; generate: string;
  generatedOutput: string;
}

interface Location {
  modifier: string; path: string; proxyPass: string; tryFiles: string;
  returnD: string; alias: string;
}

interface Server {
  listen: string[]; serverName: string; root: string; index: string;
  sslCert: string; sslCertKey: string;
  locations: Location[];
}

interface Upstream {
  name: string;
  servers: { address: string; weight: string; backup: boolean }[];
}

function indent(n: number) { return '  '.repeat(n); }

function generateConfig(servers: Server[], upstreams: Upstream[], global: Record<string, any>): string {
  let s = `# Generated by ANY-TOOL Nginx Editor\n\n`;

  if (global.workerConnections) {
    s += `events {\n${indent(1)}worker_connections ${global.workerConnections};\n}\n\n`;
  }
  s += `http {\n`;
  if (global.sendfile) s += `${indent(1)}sendfile on;\n`;
  if (global.tcpNopush) s += `${indent(1)}tcp_nopush on;\n`;
  if (global.gzip) s += `${indent(1)}gzip on;\n`;
  s += `${indent(1)}client_max_body_size ${global.clientMaxBodySize || '10m'};\n`;
  s += `${indent(1)}keepalive_timeout ${global.keepaliveTimeout || '65'};\n\n`;

  for (const up of upstreams) {
    if (!up.name || up.servers.length === 0) continue;
    s += `${indent(1)}upstream ${up.name} {\n`;
    for (const sv of up.servers) {
      if (!sv.address) continue;
      s += `${indent(2)}server ${sv.address}`;
      if (sv.weight) s += ` weight=${sv.weight}`;
      if (sv.backup) s += ` backup`;
      s += `;\n`;
    }
    s += `${indent(1)}}\n\n`;
  }

  for (const sv of servers) {
    s += `${indent(1)}server {\n`;
    for (const l of sv.listen.filter(Boolean)) s += `${indent(2)}listen ${l};\n`;
    if (sv.listen.length === 0 || sv.listen.every(x => !x)) s += `${indent(2)}listen 80;\n`;
    s += `${indent(2)}server_name ${sv.serverName || '_'};\n`;
    if (sv.root) s += `${indent(2)}root ${sv.root};\n`;
    if (sv.index) s += `${indent(2)}index ${sv.index};\n`;
    if (sv.sslCert) {
      s += `${indent(2)}ssl_certificate ${sv.sslCert};\n`;
      s += `${indent(2)}ssl_certificate_key ${sv.sslCertKey};\n`;
    }
    for (const loc of sv.locations) {
      const modPath = loc.modifier ? `${loc.modifier} ${loc.path}` : loc.path;
      s += `\n${indent(2)}location ${modPath} {\n`;
      if (loc.proxyPass) s += `${indent(3)}proxy_pass ${loc.proxyPass};\n`;
      if (loc.tryFiles) s += `${indent(3)}try_files ${loc.tryFiles};\n`;
      if (loc.returnD) s += `${indent(3)}return ${loc.returnD};\n`;
      if (loc.alias) s += `${indent(3)}alias ${loc.alias};\n`;
      s += `${indent(2)}}\n`;
    }
    s += `${indent(1)}}\n\n`;
  }
  s += `}\n`;
  return s;
}

export function NginxEditor({ labels }: { labels: Labels }) {
  const [servers, setServers] = useState<Server[]>([{ listen: ['80'], serverName: '', root: '', index: '', sslCert: '', sslCertKey: '', locations: [] }]);
  const [upstreams, setUpstreams] = useState<Upstream[]>([]);
  const [global, setGlobal] = useState({ gzip: true, clientMaxBodySize: '10m', keepaliveTimeout: '65', workerConnections: '1024', sendfile: true, tcpNopush: true });
  const [copied, setCopied] = useState(false);

  const output = generateConfig(servers, upstreams, global);

  const inputT: React.CSSProperties = {
    background: 'var(--bg)', color: 'var(--fg)', border: 'var(--border-width) solid var(--border)',
    padding: '0.4rem 0.6rem', fontFamily: 'var(--font-mono)', fontSize: '0.8rem',
    fontWeight: '700', outline: 'none',
  };
  const lbl: React.CSSProperties = { fontSize: '0.6rem', fontWeight: '800', textTransform: 'uppercase', marginBottom: '0.1rem', display: 'block' };
  const btnS: React.CSSProperties = { padding: '0.3rem 0.6rem', fontWeight: '800', fontSize: '0.6rem', textTransform: 'uppercase', cursor: 'pointer', fontFamily: 'inherit', border: '2px solid var(--border)', background: 'var(--bg)', color: 'var(--fg)', whiteSpace: 'nowrap' };
  const block: React.CSSProperties = { border: 'var(--border-width) solid var(--border)', padding: '1rem', boxShadow: '3px 3px 0px var(--border)', marginBottom: '1rem' };

  return (
    <div style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
      {/* Global */}
      <div style={block}>
        <h3 style={{ fontSize: '0.85rem', fontWeight: '800', marginBottom: '0.75rem', textTransform: 'uppercase' }}>{labels.globalSettings}</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: '0.5rem' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', fontWeight: '800', fontSize: '0.7rem', cursor: 'pointer' }}>
            <input type="checkbox" checked={global.gzip} onChange={e => setGlobal({...global, gzip: e.target.checked})} />{labels.gzip}
          </label>
          <label style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', fontWeight: '800', fontSize: '0.7rem', cursor: 'pointer' }}>
            <input type="checkbox" checked={global.sendfile} onChange={e => setGlobal({...global, sendfile: e.target.checked})} />{labels.sendfile}
          </label>
          <label style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', fontWeight: '800', fontSize: '0.7rem', cursor: 'pointer' }}>
            <input type="checkbox" checked={global.tcpNopush} onChange={e => setGlobal({...global, tcpNopush: e.target.checked})} />{labels.tcpNopush}
          </label>
          <div><span style={lbl}>{labels.workerConnections}</span><input value={global.workerConnections} onChange={e => setGlobal({...global, workerConnections: e.target.value})} style={{...inputT, width:'100%'}} /></div>
          <div><span style={lbl}>{labels.clientMaxBodySize}</span><input value={global.clientMaxBodySize} onChange={e => setGlobal({...global, clientMaxBodySize: e.target.value})} style={{...inputT, width:'100%'}} /></div>
          <div><span style={lbl}>{labels.keepaliveTimeout}</span><input value={global.keepaliveTimeout} onChange={e => setGlobal({...global, keepaliveTimeout: e.target.value})} style={{...inputT, width:'100%'}} /></div>
        </div>
      </div>

      {/* Upstreams */}
      <div style={block}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
          <h3 style={{ fontSize: '0.85rem', fontWeight: '800', textTransform: 'uppercase' }}>{labels.upstreams}</h3>
          <button onClick={() => setUpstreams([...upstreams, { name: '', servers: [] }])} style={btnS}>{labels.addUpstream}</button>
        </div>
        {upstreams.map((up, ui) => (
          <div key={ui} style={{ border: '2px solid var(--border)', padding: '0.5rem', marginBottom: '0.5rem' }}>
            <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'end', marginBottom: '0.5rem' }}>
              <div><span style={lbl}>{labels.upstreamName}</span><input value={up.name} onChange={e => { const n = [...upstreams]; n[ui] = {...up, name: e.target.value}; setUpstreams(n); }} style={{...inputT, width:'140px'}} /></div>
              <button onClick={() => setUpstreams(upstreams.filter((_,i) => i!==ui))} style={{...btnS, color:'var(--accent)'}}>{labels.remove}</button>
            </div>
            {up.servers.map((sv, si) => (
              <div key={si} style={{ display:'flex', gap:'0.3rem', alignItems:'center', marginBottom:'0.3rem', flexWrap:'wrap' }}>
                <input value={sv.address} onChange={e => { const n = [...upstreams]; n[ui].servers[si] = {...sv, address: e.target.value}; setUpstreams(n); }} placeholder="host:port" style={{...inputT, width:'200px'}} />
                <input value={sv.weight} onChange={e => { const n = [...upstreams]; n[ui].servers[si] = {...sv, weight: e.target.value}; setUpstreams(n); }} placeholder={labels.weight} style={{...inputT, width:'60px'}} />
                <label style={{ fontSize:'0.6rem', fontWeight:'700', display:'flex', alignItems:'center', gap:'0.2rem' }}>
                  <input type="checkbox" checked={sv.backup} onChange={e => { const n = [...upstreams]; n[ui].servers[si] = {...sv, backup: e.target.checked}; setUpstreams(n); }} />{labels.backup}
                </label>
                <button onClick={() => { const n = [...upstreams]; n[ui].servers.splice(si,1); setUpstreams(n); }} style={{...btnS, fontSize:'0.55rem'}}>{labels.remove}</button>
              </div>
            ))}
            <button onClick={() => { const n=[...upstreams]; n[ui].servers.push({address:'',weight:'',backup:false}); setUpstreams(n); }} style={btnS}>{labels.addUpstreamServer}</button>
          </div>
        ))}
      </div>

      {/* Servers */}
      <div style={block}>
        <div style={{ display: 'flex', justifyContent:'space-between', marginBottom:'0.5rem' }}>
          <h3 style={{ fontSize:'0.85rem', fontWeight:'800', textTransform:'uppercase' }}>{labels.servers}</h3>
          <button onClick={() => setServers([...servers, { listen:['80'], serverName:'', root:'', index:'', sslCert:'', sslCertKey:'', locations:[] }])} style={btnS}>{labels.addServer}</button>
        </div>
        {servers.map((sv, si) => (
          <div key={si} style={{ border:'2px solid var(--border)', padding:'0.75rem', marginBottom:'0.75rem', position:'relative' }}>
            <button onClick={() => setServers(servers.filter((_,i)=>i!==si))} style={{...btnS, position:'absolute', top:'0.25rem', right:'0.25rem', color:'var(--accent)'}}>{labels.remove}</button>
            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'0.5rem', marginBottom:'0.5rem' }}>
              <div>
                <span style={lbl}>{labels.listen}</span>
                {sv.listen.map((l, li) => (
                  <div key={li} style={{ display:'flex', gap:'0.3rem', marginBottom:'0.2rem' }}>
                    <input value={l} onChange={e => { const n=[...servers]; n[si].listen[li]=e.target.value; setServers(n); }} placeholder="80" style={{...inputT, width:'100%'}} />
                    {sv.listen.length > 1 && <button onClick={() => { const n=[...servers]; n[si].listen.splice(li,1); setServers(n); }} style={{...btnS, fontSize:'0.55rem', color:'var(--accent)'}}>{labels.remove}</button>}
                  </div>
                ))}
                <button onClick={() => { const n=[...servers]; n[si].listen.push(''); setServers(n); }} style={btnS}>+</button>
              </div>
              <div><span style={lbl}>{labels.serverName}</span><input value={sv.serverName} onChange={e => { const n=[...servers]; n[si]={...sv, serverName: e.target.value}; setServers(n); }} placeholder="example.com" style={{...inputT, width:'100%'}} /></div>
              <div><span style={lbl}>{labels.root}</span><input value={sv.root} onChange={e => { const n=[...servers]; n[si]={...sv, root: e.target.value}; setServers(n); }} style={{...inputT, width:'100%'}} /></div>
              <div><span style={lbl}>{labels.index}</span><input value={sv.index} onChange={e => { const n=[...servers]; n[si]={...sv, index: e.target.value}; setServers(n); }} style={{...inputT, width:'100%'}} /></div>
            </div>

            {/* SSL */}
            <div style={{ marginBottom:'0.5rem' }}>
              <span style={{...lbl, cursor:'pointer'}} onClick={() => { const n=[...servers]; const has = !!n[si].sslCert; n[si]={...sv, sslCert: has?'':'/path/to/cert.pem', sslCertKey: has?'':'/path/to/key.pem'}; setServers(n); }}>
                {labels.ssl} {sv.sslCert ? '▼' : '▶'}
              </span>
              {sv.sslCert && (
                <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'0.3rem', marginTop:'0.3rem' }}>
                  <input value={sv.sslCert} onChange={e => { const n=[...servers]; n[si]={...sv, sslCert: e.target.value}; setServers(n); }} placeholder={labels.sslCert} style={{...inputT, width:'100%'}} />
                  <input value={sv.sslCertKey} onChange={e => { const n=[...servers]; n[si]={...sv, sslCertKey: e.target.value}; setServers(n); }} placeholder={labels.sslCertKey} style={{...inputT, width:'100%'}} />
                </div>
              )}
            </div>

            {/* Locations */}
            <div>
              <div style={{ display:'flex', justifyContent:'space-between', marginBottom:'0.25rem' }}>
                <span style={lbl}>{labels.locations}</span>
                <button onClick={() => { const n=[...servers]; n[si].locations.push({ modifier:'', path:'/', proxyPass:'', tryFiles:'', returnD:'', alias:'' }); setServers(n); }} style={btnS}>{labels.addLocation}</button>
              </div>
              {sv.locations.map((loc, li) => (
                <div key={li} style={{ border:'1.5px solid var(--border)', padding:'0.5rem', marginBottom:'0.4rem', background:'rgba(0,0,0,0.02)' }}>
                  <div style={{ display:'flex', gap:'0.3rem', marginBottom:'0.3rem', flexWrap:'wrap' }}>
                    <select value={loc.modifier} onChange={e => { const n=[...servers]; n[si].locations[li]={...loc, modifier: e.target.value}; setServers(n); }} style={{...inputT, width:'auto'}}>
                      <option value="">(none)</option><option value="=">= exact</option><option value="~">~ regex</option><option value="~*">~* regex ci</option><option value="^~">^~ prefix</option>
                    </select>
                    <input value={loc.path} onChange={e => { const n=[...servers]; n[si].locations[li]={...loc, path: e.target.value}; setServers(n); }} placeholder={labels.path} style={{...inputT, flex:1}} />
                    <button onClick={() => { const n=[...servers]; n[si].locations.splice(li,1); setServers(n); }} style={{...btnS, fontSize:'0.55rem', color:'var(--accent)'}}>{labels.remove}</button>
                  </div>
                  <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'0.3rem' }}>
                    <input value={loc.proxyPass} onChange={e => { const n=[...servers]; n[si].locations[li]={...loc, proxyPass: e.target.value}; setServers(n); }} placeholder={labels.proxyPass} style={{...inputT, width:'100%'}} />
                    <input value={loc.tryFiles} onChange={e => { const n=[...servers]; n[si].locations[li]={...loc, tryFiles: e.target.value}; setServers(n); }} placeholder={labels.tryFiles} style={{...inputT, width:'100%'}} />
                    <input value={loc.returnD} onChange={e => { const n=[...servers]; n[si].locations[li]={...loc, returnD: e.target.value}; setServers(n); }} placeholder={labels.returnD} style={{...inputT, width:'100%'}} />
                    <input value={loc.alias} onChange={e => { const n=[...servers]; n[si].locations[li]={...loc, alias: e.target.value}; setServers(n); }} placeholder={labels.alias} style={{...inputT, width:'100%'}} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Output */}
      <div style={block}>
        <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'0.5rem' }}>
          <h3 style={{ fontSize:'0.85rem', fontWeight:'800', textTransform:'uppercase' }}>{labels.generatedOutput}</h3>
          <button onClick={() => { navigator.clipboard.writeText(output); setCopied(true); setTimeout(() => setCopied(false), 1500); }} style={btnS}>{copied ? labels.copied : labels.copy}</button>
        </div>
        <pre style={{ background:'rgba(0,0,0,0.03)', padding:'0.75rem', fontFamily:'var(--font-mono)', fontSize:'0.72rem', lineHeight:1.5, overflow:'auto', maxHeight:'500px', whiteSpace:'pre', margin:0 }}>{output}</pre>
      </div>
    </div>
  );
}
